/*
 * To change this t

            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }mplate, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Jan 8, 2012, 5:49:15 PM
 */
/**
 *
 * @author mukesh
 */
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        jobin();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void jobin()
    {
        setIconImage(new ImageIcon("images/Flights.gif").getImage());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_email = new javax.swing.JLabel();
        jButton1_selectionsummery = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4_login = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3_logiin_logo = new javax.swing.JLabel();
        jLabel3_already = new javax.swing.JLabel();
        jLabel3_email = new javax.swing.JLabel();
        jLabel3_pass = new javax.swing.JLabel();
        jLabel3_forgotpass = new javax.swing.JLabel();
        jTextField1_email1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton4_loginpass = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4_continue_booking = new javax.swing.JLabel();
        jLabel4_continue_texy = new javax.swing.JLabel();
        jLabel4_continue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1_email = new javax.swing.JTextField();
        jTextField2_re_email = new javax.swing.JTextField();
        jTextField3_mobile = new javax.swing.JTextField();
        jButton4_continue = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenuItem1_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book n Fly");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));
        jPanel1.add(jLabel1_email);
        jLabel1_email.setBounds(10, 10, 1000, 630);
        jLabel1_email.add(jButton2);

        jButton1_selectionsummery.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1_selectionsummery.setText("Select your Flight                                                                                                                                                                                                ");
        jButton1_selectionsummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_selectionsummeryActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_selectionsummery);
        jButton1_selectionsummery.setBounds(10, 10, 1000, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Payment Details                                                                                                                                                         ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 610, 1000, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Passenger Details                                                                                                                                                       ");
        jButton3.setMaximumSize(new java.awt.Dimension(750, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(750, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 570, 1000, 25);

        jButton4_login.setBackground(new java.awt.Color(204, 204, 204));
        jButton4_login.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4_login.setText("Login/ Contact Details                                                                                                                                                                                         ");
        jPanel1.add(jButton4_login);
        jButton4_login.setBounds(10, 50, 1000, 25);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 8, true));
        jPanel2.setLayout(null);

        jLabel3_logiin_logo.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3_logiin_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoorignl.jpg"))); // NOI18N
        jPanel2.add(jLabel3_logiin_logo);
        jLabel3_logiin_logo.setBounds(70, 10, 265, 82);

        jLabel3_already.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3_already.setText("Already a member?");
        jPanel2.add(jLabel3_already);
        jLabel3_already.setBounds(60, 120, 160, 17);

        jLabel3_email.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3_email.setText("Email");
        jPanel2.add(jLabel3_email);
        jLabel3_email.setBounds(60, 190, 50, 14);

        jLabel3_pass.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3_pass.setText("Password");
        jPanel2.add(jLabel3_pass);
        jLabel3_pass.setBounds(60, 264, 70, 20);

        jLabel3_forgotpass.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3_forgotpass.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3_forgotpass.setText("Forgot Password");
        jLabel3_forgotpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_forgotpassMouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3_forgotpass);
        jLabel3_forgotpass.setBounds(60, 330, 90, 20);
        jPanel2.add(jTextField1_email1);
        jTextField1_email1.setBounds(160, 190, 150, 20);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(160, 260, 150, 20);

        jButton4_loginpass.setBackground(new java.awt.Color(255, 153, 51));
        jButton4_loginpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4_loginpass.setText("Login");
        jButton4_loginpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_loginpassActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4_loginpass);
        jButton4_loginpass.setBounds(180, 330, 90, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 120, 420, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/or_long.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(470, 110, 80, 430);

        jLabel4_continue_booking.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4_continue_booking.setText("Continue booking as a Guest?");
        jPanel1.add(jLabel4_continue_booking);
        jLabel4_continue_booking.setBounds(600, 120, 220, 17);

        jLabel4_continue_texy.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4_continue_texy.setText("We required your Email id and Mobile number");
        jPanel1.add(jLabel4_continue_texy);
        jLabel4_continue_texy.setBounds(600, 160, 340, 20);

        jLabel4_continue.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4_continue.setText("to send you booking details Via Email and SMS");
        jPanel1.add(jLabel4_continue);
        jLabel4_continue.setBounds(600, 190, 320, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel4.setText("E-mail");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(600, 270, 50, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setText("Re enter E-mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(600, 320, 90, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel6.setText("Mobile Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 370, 90, 14);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jCheckBox1.setText("I have agreed the terms and conditions");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(600, 420, 240, 23);

        jTextField1_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1_emailMouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1_email);
        jTextField1_email.setBounds(720, 270, 180, 20);
        String email=jTextField1_email.getText();

        jTextField2_re_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField2_re_emailMouseExited(evt);
            }
        });
        jPanel1.add(jTextField2_re_email);
        jTextField2_re_email.setBounds(720, 320, 180, 20);

        jTextField3_mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3_mobileMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField3_mobileMouseExited(evt);
            }
        });
        jTextField3_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_mobileActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3_mobile);
        jTextField3_mobile.setBounds(720, 370, 180, 20);

        jButton4_continue.setBackground(new java.awt.Color(255, 153, 51));
        jButton4_continue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4_continue.setText("Continue");
        jButton4_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_continueActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_continue);
        jButton4_continue.setBounds(760, 470, 100, 23);

        jProgressBar1.setForeground(new java.awt.Color(255, 153, 51));
        jProgressBar1.setToolTipText("progress");
        jProgressBar1.setValue(15);
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(850, 90, 146, 17);
        jProgressBar1.setValue(20);
        jProgressBar1.setVisible(false);

        jProgressBar1.setStringPainted(true);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 680);

        menu_file.setBackground(new java.awt.Color(204, 51, 0));
        menu_file.setText("File      ");
        menu_file.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jMenuItem1_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem1_exit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jMenuItem1_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jMenuItem1_exit.setText("Exit");
        jMenuItem1_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_exitActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem1_exit);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel3_forgotpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_forgotpassMouseClicked
JOptionPane.showMessageDialog(null,"YOUR REQUEST CANNOT BE PROCESSED, PLEASE RE-REGISTER WITH US!!!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3_forgotpassMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton4_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_continueActionPerformed
if(jCheckBox1.getSelectedObjects()==null) 
{
    //JOptionPane.showMessageDialog(null,"please accept terms");
    jCheckBox1.setForeground(Color.red);
    JOptionPane.showMessageDialog(null,"please Tick");
   
}
else
{
    
   boolean flag = true;
   
   int Mobile_Number=0;
   try
                                        {
						Mobile_Number = Integer.parseInt(jTextField3_mobile.getText());
				    }
                                        catch(Exception ex){
				    	JOptionPane.showMessageDialog(null,   "Invalid Mobile Number !");	
				    	flag = false;
				   		 
				    }
   if(      jTextField1_email.getText() == null ? (jTextField2_re_email.getText()) != null : !jTextField1_email.getText().equals(jTextField2_re_email.getText()))
   {
     JOptionPane.showMessageDialog(null,"Email doesn't match");
     jTextField2_re_email.setForeground(Color.red);
     flag=false;
   }
    
     String Email=jTextField1_email.getText(); 

    if(flag)
    {
        try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="insert into customer_info(email,mobile) values('"+Email+"','"+Mobile_Number+"')";
							st.executeUpdate(sql);
                                                        jTextField2_re_email.setForeground(Color.black);
                                                        new Login1().setVisible(true);
							//JOptionPane.showMessageDialog(null,"Data Inserted");
						}catch(Exception er){
							System.out.println(er);
						}
    }
    
    
    
    
    
    
   // new Login1().setVisible(true);
    jCheckBox1.setForeground(Color.black);
   // dispose();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4_continueActionPerformed

    private void jButton4_loginpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_loginpassActionPerformed

        String email_get=jTextField1_email1.getText();
        String pass=jPasswordField1.getText();
 
        
        
        
               
        if(     "".equals(jTextField1_email1.getText()))
           
{
    JOptionPane.showMessageDialog(null, "Invalid Email");
}
else if ("".equals(jPasswordField1.getText()))
{ 
 JOptionPane.showMessageDialog(null, "Invalid password");   
}

        else if(("admin".equals(email_get))&&(("admin".equals(pass))))
{
    
new search_home().setVisible(true);
dispose();
    
}
        
// else{
  //  JOptionPane.showMessageDialog(null, "invalid login, please try again");
//}       
        
        
        boolean flag=false;
        
          try
{
            	Connection con=NewCon.connect();
				Statement st=con.createStatement();
				String sql="select * from customer_info where email='"+email_get+"' and password='"+pass+"'";
                ResultSet rs=st.executeQuery(sql);
                while(rs.next())
                {
                   flag=true;
                    new search_home1().setVisible(true);   
                   
                   dispose();
                   
                }
              //  System.out.println(pass);
                
}
                 
catch(Exception ex)
			{
				//System.out.println(ex);
                                 //JOptionPane.showMessageDialog(null, "invalid login, please try again");
			}  
        
        if(flag)
        {
          String status="not booked";
            
             try
{
            	Connection con=NewCon.connect();
				Statement st=con.createStatement();
				String sql="insert into login (name,status) values('"+email_get+"','"+status+"')";
                 st.executeUpdate(sql);
              //  System.out.println(pass);
                
}
                 
catch(Exception ex)
			{
				System.out.println(ex);
                                 
			}  
            
            
            
            
        }
 
else
        {
     JOptionPane.showMessageDialog(null, "invalid login, please try again");       
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_loginpassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1_selectionsummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_selectionsummeryActionPerformed
new search_home1().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_selectionsummeryActionPerformed

    private void jTextField3_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_mobileActionPerformed

    private void jTextField3_mobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3_mobileMouseClicked

       // jProgressBar1.setVisible(true);  
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_mobileMouseClicked

    private void jTextField2_re_emailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_re_emailMouseExited
   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_re_emailMouseExited

    private void jTextField1_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1_emailMouseClicked
    
        jProgressBar1.setVisible(true);
        jProgressBar1.setValue(0);


jProgressBar1.setString("0%"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailMouseClicked

    private void jTextField3_mobileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3_mobileMouseExited
      
        
        jProgressBar1.setValue(15);


jProgressBar1.setString("15%");  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_mobileMouseExited

    private void jMenuItem1_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_exitActionPerformed
int reply=JOptionPane.showConfirmDialog(null,"sure, You want to quit");
if(reply==JOptionPane.OK_OPTION)
{
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_exitActionPerformed

       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_selectionsummery;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_continue;
    private javax.swing.JButton jButton4_login;
    private javax.swing.JButton jButton4_loginpass;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1_email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_already;
    private javax.swing.JLabel jLabel3_email;
    private javax.swing.JLabel jLabel3_forgotpass;
    private javax.swing.JLabel jLabel3_logiin_logo;
    private javax.swing.JLabel jLabel3_pass;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_continue;
    private javax.swing.JLabel jLabel4_continue_booking;
    private javax.swing.JLabel jLabel4_continue_texy;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField1_email1;
    private javax.swing.JTextField jTextField2_re_email;
    private javax.swing.JTextField jTextField3_mobile;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables
}
