/*
 * To change this t

            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }mplate, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login1.java
 *
 * Created on Jan 8, 2012, 5:49:15 PM
 */
/**
 *
 * @author jobin
 */
//import com.sun.xml.internal.bind.v2.model.core.ID;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
public class Login1 extends javax.swing.JFrame {

    /** Creates new form Login1 */
    public Login1() {
        jobin();
        mail();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void jobin()
    {
        setIconImage(new ImageIcon("images/Flights.gif").getImage());
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1_selection = new javax.swing.JButton();
        jButton2_payment = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4_login = new javax.swing.JButton();
        jTextField1_email = new javax.swing.JTextField();
        jTextField4_firstname = new javax.swing.JTextField();
        jTextField5_lastname = new javax.swing.JTextField();
        jTextField6_mobile = new javax.swing.JTextField();
        jTextField7_address1 = new javax.swing.JTextField();
        jTextField8_city = new javax.swing.JTextField();
        jTextField9_state = new javax.swing.JTextField();
        jTextField10_pin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1_title = new javax.swing.JComboBox();
        jComboBox2_month = new javax.swing.JComboBox();
        jComboBox3_day = new javax.swing.JComboBox();
        jComboBox4_year = new javax.swing.JComboBox();
        jComboBox5_nationality = new javax.swing.JComboBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2_confirm = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jButton4_continue = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2_address2 = new javax.swing.JTextField();
        jButton4_continue1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenuItem1_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book n Fly");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 1000, 630);
        jLabel1.add(jButton2_payment);

        jButton1_selection.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1_selection.setText("Selection Summery                                                                                                                                                                                                ");
        jButton1_selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_selectionActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_selection);
        jButton1_selection.setBounds(10, 10, 1000, 25);

        jButton2_payment.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2_payment.setText("Payment Details                                                                                                                                                         ");
        jButton2_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_paymentActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2_payment);
        jButton2_payment.setBounds(10, 610, 1000, 25);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Passenger Details                                                                                                                                                                                                ");
        jButton3.setMaximumSize(new java.awt.Dimension(750, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(750, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 90, 1000, 25);

        jButton4_login.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4_login.setText("Login/ Contact Details                                                                                                                                                                                         ");
        jButton4_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_login);
        jButton4_login.setBounds(10, 50, 1000, 25);

        jTextField1_email.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField1_email.setToolTipText("Fill the text Field");
        jTextField1_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField1_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_emailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_email);
        jTextField1_email.setBounds(30, 260, 150, 19);
        try
        {
            Connection con=NewCon.connect();
            Statement st=con.createStatement();
            String sql="select email from customer_info";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                jTextField1_email.setText(rs.getString(1));

            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }

        jTextField4_firstname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField4_firstname.setToolTipText("Fill the text Field");
        jTextField4_firstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField4_firstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4_firstnameMouseClicked(evt);
            }
        });
        jPanel1.add(jTextField4_firstname);
        jTextField4_firstname.setBounds(190, 360, 150, 19);

        jTextField5_lastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5_lastname.setToolTipText("Fill the text Field");
        jTextField5_lastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jTextField5_lastname);
        jTextField5_lastname.setBounds(350, 360, 150, 19);

        jTextField6_mobile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6_mobile.setToolTipText("Fill the text Field");
        jTextField6_mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField6_mobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6_mobileMouseClicked(evt);
            }
        });
        jPanel1.add(jTextField6_mobile);
        jTextField6_mobile.setBounds(680, 360, 150, 19);

        jTextField7_address1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7_address1.setToolTipText("Fill the text Field");
        jTextField7_address1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jTextField7_address1);
        jTextField7_address1.setBounds(30, 470, 150, 19);

        jTextField8_city.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField8_city.setToolTipText("Fill the text Field");
        jTextField8_city.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jTextField8_city);
        jTextField8_city.setBounds(350, 470, 150, 19);

        jTextField9_state.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField9_state.setToolTipText("Fill the text Field");
        jTextField9_state.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jTextField9_state);
        jTextField9_state.setBounds(680, 470, 150, 20);

        jTextField10_pin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField10_pin.setToolTipText("Fill the text Field");
        jTextField10_pin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField10_pin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10_pinMouseClicked(evt);
            }
        });
        jPanel1.add(jTextField10_pin);
        jTextField10_pin.setBounds(840, 470, 160, 19);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel2.setText("Passport Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(680, 330, 160, 17);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel3.setText("Email*");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 230, 110, 17);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel4.setText("Password*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 230, 110, 17);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel5.setText("Confirm Password*");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 230, 150, 17);

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel6.setText("Title*");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 330, 110, 17);

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel7.setText("First Name*");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 330, 110, 17);

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel8.setText("Last Name");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 330, 110, 17);

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel9.setText("Pin Code*");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(840, 440, 110, 17);

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel10.setText("Date Of Birth");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 330, 110, 17);

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel11.setText("Address Line1*");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 440, 110, 17);

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel12.setText("City*");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(350, 440, 110, 17);

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel13.setText("State*");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(680, 440, 110, 17);

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel14.setText("Country*");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(510, 440, 110, 17);

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 0, 14));
        jLabel15.setText("Address-line2");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(190, 440, 110, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel16.setText("Please provide the following Details to register..");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 160, 350, 17);

        jComboBox1_title.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1_title.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Mr.", "Mrs", "Ms." }));
        jComboBox1_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_titleActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1_title);
        jComboBox1_title.setBounds(30, 360, 100, 23);

        jComboBox2_month.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox2_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(jComboBox2_month);
        jComboBox2_month.setBounds(560, 360, 50, 23);

        jComboBox3_day.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox3_day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox3_day);
        jComboBox3_day.setBounds(510, 360, 50, 23);

        jComboBox4_year.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox4_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990" }));
        jPanel1.add(jComboBox4_year);
        jComboBox4_year.setBounds(610, 360, 60, 23);

        jComboBox5_nationality.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox5_nationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "India", "australia", "UAE", "USA" }));
        jPanel1.add(jComboBox5_nationality);
        jComboBox5_nationality.setBounds(510, 470, 150, 23);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPasswordField1.setToolTipText("Paassword");
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(190, 260, 150, 19);

        jPasswordField2_confirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPasswordField2_confirm.setToolTipText("Paassword");
        jPasswordField2_confirm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordField2_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2_confirmMouseClicked(evt);
            }
        });
        jPanel1.add(jPasswordField2_confirm);
        jPasswordField2_confirm.setBounds(350, 260, 150, 19);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(255, 153, 51));
        jProgressBar1.setToolTipText("progress");
        jProgressBar1.setValue(15);
        jProgressBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(860, 130, 148, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel17.setText("Profile Completion....");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(860, 160, 120, 15);

        jButton4_continue.setBackground(new java.awt.Color(255, 153, 51));
        jButton4_continue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4_continue.setText("Continue Booking");
        jButton4_continue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton4_continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_continueActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_continue);
        jButton4_continue.setBounds(840, 540, 160, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoorignl.jpg"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(30, 140, 230, 50);

        jLabel19.setText("*Required, must fill");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 580, 130, 14);

        jTextField2_address2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2_address2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField2_address2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_address2MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField2_address2);
        jTextField2_address2.setBounds(190, 470, 150, 19);

        jButton4_continue1.setBackground(new java.awt.Color(255, 153, 51));
        jButton4_continue1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4_continue1.setText("Search another Flight");
        jButton4_continue1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton4_continue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_continue1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_continue1);
        jButton4_continue1.setBounds(650, 540, 160, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 680);

        menu_file.setBackground(new java.awt.Color(204, 51, 0));
        menu_file.setText("File      ");
        menu_file.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jMenuItem1_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem1_exit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jMenuItem1_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jMenuItem1_exit.setText("Exit");
        jMenuItem1_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_exitActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem1_exit);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        new UserRegistration().setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_paymentActionPerformed
JOptionPane.showMessageDialog(null,"please fill all the field and click CONTINUE");        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton2_paymentActionPerformed

    private void jButton1_selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_selectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_selectionActionPerformed

    private void jComboBox1_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_titleActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton4_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_loginActionPerformed
new Login().setVisible(true);
mail();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4_loginActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
jProgressBar1.setValue(25);


jProgressBar1.setString("25%");        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2_confirmMouseClicked
jProgressBar1.setValue(35);


jProgressBar1.setString("35%");         // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2_confirmMouseClicked

    private void jTextField4_firstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4_firstnameMouseClicked
jProgressBar1.setValue(45);


jProgressBar1.setString("45%");         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_firstnameMouseClicked

    private void jTextField6_mobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6_mobileMouseClicked
jProgressBar1.setValue(50);


jProgressBar1.setString("50%");         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6_mobileMouseClicked

    private void jTextField2_address2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_address2MouseClicked
jProgressBar1.setValue(60);


jProgressBar1.setString("60%");         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_address2MouseClicked

    private void jTextField10_pinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10_pinMouseClicked
jProgressBar1.setValue(70);


jProgressBar1.setString("70%");         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_pinMouseClicked

    private void jTextField1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailActionPerformed

    private void jButton4_continueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_continueActionPerformed

        String email=jTextField1_email.getText();
        String password=jPasswordField1.getText();
//System.out.println(password);
         String repass=jPasswordField2_confirm.getText();
        String tittle=(String)jComboBox1_title.getSelectedItem();
        String firstname=jTextField4_firstname.getText();
        String lastname=jTextField5_lastname.getText();
        String day=(String)jComboBox3_day.getSelectedItem();
        String month=(String)jComboBox2_month.getSelectedItem();
        String year=(String)jComboBox4_year.getSelectedItem();
        String date=year+"/"+month+"/"+day;
        String address1=jTextField7_address1.getText();
        String address2=jTextField2_address2.getText();
        String city=jTextField8_city.getText();
        String country=(String)jComboBox5_nationality.getSelectedItem();
        String state=jTextField9_state.getText();
        int pin=0;
         
         
         
           boolean flag=false;
         
         
         if(     "".equals(jPasswordField1.getText()))
           
{
    JOptionPane.showMessageDialog(null, "Invalid password");
}
           else if(      jPasswordField1.getText() == null ? (jPasswordField2_confirm.getText()) != null : !jPasswordField1.getText().equals(jPasswordField2_confirm.getText()))
   {
     JOptionPane.showMessageDialog(null,"Password doesn't match");
     jPasswordField2_confirm.setForeground(Color.red);
     flag=false;
   }
          
                 
                 
                 
else if ("".equals(jTextField4_firstname.getText()))
{ 
 flag=false;
}

    else if ("".equals(jTextField7_address1.getText()))
{ 
 flag=false;
}
             else if ("".equals(jTextField8_city.getText()))
{ 
 flag=false;
}  
             else if ("".equals(jTextField9_state.getText()))
{ 
 flag=false;
}  
         
             else if ("Title".equals(jComboBox1_title.getSelectedItem()))
{ 
     JOptionPane.showMessageDialog(null,"Select your title");   
 flag=false;
}  
         
         if(year=="yyyy")
{
    JOptionPane.showMessageDialog(null,"invalid year");
    flag=false;
}
else if(month=="mm")
{
    JOptionPane.showMessageDialog(null,"invalid month");
    flag=false;
}
else if(day=="dd")
{
    JOptionPane.showMessageDialog(null,"invalid date");
    flag=false;
}
         int passport_number=0;
         
                
     try
                                        {
						passport_number =Integer.parseInt(jTextField6_mobile.getText());
                                                flag=true;
				    }
                                        catch(Exception ex){
				    	JOptionPane.showMessageDialog(null,   "Invalid passport !");	
				    	flag = false;
				   		 
				    }
       
        try
                                        {
						pin =Integer.parseInt(jTextField10_pin.getText());
                                                flag=true;
				    }
                                        catch(Exception ex){
				    	JOptionPane.showMessageDialog(null,   "Invalid pin number !");	
				    	flag = false;
				   		 
				    }
        									
					if(flag){
						//do database write	
						try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="update customer_info set password='"+password+"',title='"+tittle+"',name='"+firstname+"',name_last='"+lastname+"',Date='"+date+"',address1='"+address1+"',address2='"+address2+"',city='"+city+"',country='"+country+"',state='"+state+"',pincode='"+pin+"',passport='"+passport_number+"' where email='"+email+"'";
                                                 //)";
							
                                                 st.executeUpdate(sql);
							//JOptionPane.showMessageDialog(null,"Data Inserted");
                                                        new payment().setVisible(true);
                                                        
						}catch(Exception er){
							System.out.println(er);
						}
				}
				else
                                        {
                                         JOptionPane.showMessageDialog(null,"Please fill all the required fields");   
                                        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_continueActionPerformed

    private void jMenuItem1_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_exitActionPerformed
int reply=JOptionPane.showConfirmDialog(null,"sure");  
if(reply==JOptionPane.OK_OPTION)
{
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_exitActionPerformed

    private void jButton4_continue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_continue1ActionPerformed
new search_home1().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4_continue1ActionPerformed

    public void mail()
    {
         Login friam=new Login();
           String mm=friam.jTextField1_email.getText();
           
//         jTextField1.setText(mm);
             System.out.print(mm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login1().setVisible(true);
             
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_selection;
    private javax.swing.JButton jButton2_payment;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_continue;
    private javax.swing.JButton jButton4_continue1;
    private javax.swing.JButton jButton4_login;
    private javax.swing.JComboBox jComboBox1_title;
    private javax.swing.JComboBox jComboBox2_month;
    private javax.swing.JComboBox jComboBox3_day;
    private javax.swing.JComboBox jComboBox4_year;
    private javax.swing.JComboBox jComboBox5_nationality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2_confirm;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField10_pin;
    private javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField2_address2;
    private javax.swing.JTextField jTextField4_firstname;
    private javax.swing.JTextField jTextField5_lastname;
    private javax.swing.JTextField jTextField6_mobile;
    private javax.swing.JTextField jTextField7_address1;
    private javax.swing.JTextField jTextField8_city;
    private javax.swing.JTextField jTextField9_state;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables
}
