/*
 * To change this t

            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }mplate, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * payment.java
 *
 * Created on Jan 8, 2012, 5:49:15 PM
 */
/**
 *
 * @author jobin
 */
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JPasswordField;
public class payment extends javax.swing.JFrame {

    /** Creates new form payment */
    public payment() {
        jobin();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void jobin()
    {
        setIconImage(new ImageIcon("images/Flights.gif").getImage());
        buttonGroup1=new ButtonGroup();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
       
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_email = new javax.swing.JLabel();
        jButton1_selectionsummery = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4_login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2_card_validity = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField2_card_number1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenuItem1_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book n Fly");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1_email.setText("                                                    ");
        jLabel1_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));
        jPanel1.add(jLabel1_email);
        jLabel1_email.setBounds(10, 10, 1000, 630);
        jLabel1_email.add(jButton2);

        jButton1_selectionsummery.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1_selectionsummery.setText("Selection Summery                                                                                                                                                                                                ");
        jButton1_selectionsummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_selectionsummeryActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_selectionsummery);
        jButton1_selectionsummery.setBounds(10, 10, 1000, 25);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Thank you for your interest                                                                                                                                                    ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 610, 1000, 25);

        jButton4_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_login.setText("Search home                                                                                                                                                                                                         ");
        jButton4_login.setInheritsPopupMenu(true);
        jButton4_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_login);
        jButton4_login.setBounds(10, 40, 1000, 25);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(640, 150, 0, 20);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 150, 0, 20);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 150, 0, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton1.setText("Login with an other id");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 470, 160, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton4.setText("Search another Flight");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(70, 470, 160, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel5.setText("Card number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 340, 120, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setText("Welcome,");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 140, 70, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel10.setText("Please provide your Card detais");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 250, 250, 17);

        jTextField2_card_validity.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(jTextField2_card_validity);
        jTextField2_card_validity.setBounds(450, 380, 170, 23);

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(250, 380, 170, 23);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jRadioButton1.setText("OTHERS");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(700, 250, 180, 25);
        buttonGroup1.add(jRadioButton2);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jRadioButton2.setText("MASTER CARD");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(520, 250, 140, 25);
        buttonGroup1.add(jRadioButton1);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jRadioButton3.setText("VISA");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(380, 250, 140, 25);
        buttonGroup1.add(jRadioButton3);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoorignl.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 130, 270, 140);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Payment Details                                                                                                                                                                                                    ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 70, 1000, 25);

        jButton5.setBackground(new java.awt.Color(255, 153, 51));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("Continue to pay..");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(660, 450, 240, 60);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jButton6.setText("Change your Personal details");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(260, 470, 160, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel11.setText("Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(250, 340, 120, 17);

        jTextField2_card_number1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(jTextField2_card_number1);
        jTextField2_card_number1.setBounds(40, 380, 170, 23);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel12.setText("Validity");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(450, 340, 120, 17);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 140, 180, 17);
        try
        {
            Connection con=NewCon.connect();
            Statement st=con.createStatement();
            String sql="select name from customer_info";
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                jTextField1.setText(rs.getString(1));

            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 680);

        menu_file.setBackground(new java.awt.Color(204, 51, 0));
        menu_file.setText("File      ");
        menu_file.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jMenuItem1_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem1_exit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jMenuItem1_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jMenuItem1_exit.setText("Exit");
        jMenuItem1_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_exitActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem1_exit);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1_selectionsummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_selectionsummeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_selectionsummeryActionPerformed

    private void jButton4_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_loginActionPerformed
new search_home1().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4_loginActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new search_home1().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Login().setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
boolean flag=false; 
        String cardtype="";
        if(jRadioButton1.isSelected())
        {
            cardtype="visa";
        }
        else if(jRadioButton2.isSelected())
                {
                    cardtype="master";
                }
        else if(jRadioButton3.isSelected())
        {
            cardtype="other";
        }
        
        else if(buttonGroup1.isSelected(null))
        {
             JOptionPane.showMessageDialog(null,"Select your card type");
             flag=false;
        }
        String password=jPasswordField1.getText();
        String car_validity=jTextField2_card_validity.getText();
        String name=jTextField1.getText();
        int card_number=0;
       
if(     "".equals(jPasswordField1.getText()))
    {
       JOptionPane.showMessageDialog(null,   "Invalid password !");	 
       flag=false;
    }
        
       
       
        try
                                        {
						card_number =Integer.parseInt(jTextField2_card_number1.getText());
                                                flag=true;
                                                //System.out.println(card_number);
				    }
                                        catch(Exception ex){
				    	JOptionPane.showMessageDialog(null,   "Invalid card number !");	
				    	flag = false;
				   		 
				    }
        									
					if(flag){
						//do database write	
						try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="update customer_info set credit_no='"+card_number+"',credit_validity='"+car_validity+"',credit_type='"+cardtype+"' where name='"+name+"'";
                                                 //)";
							
                                                 st.executeUpdate(sql);
							JOptionPane.showMessageDialog(null,"Congradulations, Your Database is Created Successfully");
                                                        new search_home1().setVisible(true);
                                                        
						}catch(Exception er){
                                                    JOptionPane.showMessageDialog(null, "invalid date");
                                                    jTextField2_card_validity.setForeground(Color.red);
							System.out.println(er);
						}
				}
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_exitActionPerformed
int reply=JOptionPane.showConfirmDialog(null,"Are you sure want to exit?7");  
if(reply==JOptionPane.OK_OPTION)
{
    System.exit(0);
}
    }//GEN-LAST:event_jMenuItem1_exitActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
new Login1().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_selectionsummery;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton4_login;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1_email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2_card_number1;
    private javax.swing.JTextField jTextField2_card_validity;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables
}
