/*
 * To change this t

            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet.");
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }mplate, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * search_home.java
 *
 * Created on Jan 8, 2012, 5:49:15 PM
 */
/**
 *
 * @author jobin
 */
//import com.sun.corba.se.impl.protocol.giopmsgheaders.ReplyMessage;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
public class search_home extends javax.swing.JFrame {

    /** Creates new form search_home */
    public search_home() {
        jobin();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void jobin()
    {
        setIconImage(new ImageIcon("images/Flights.gif").getImage());
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_email = new javax.swing.JLabel();
        jButton1_selectionsummery = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4_login = new javax.swing.JButton();
        jLabel1_add_flight_details = new javax.swing.JLabel();
        jButton1_Edit_fligt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7_fupdate_both = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4_flight_noboth = new javax.swing.JComboBox();
        jComboBox5_destination_both = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5_arr = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4_source_both = new javax.swing.JComboBox();
        jTextField1_date = new javax.swing.JTextField();
        jTextField2_dept_time = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton7_search_using_flight_no = new javax.swing.JButton();
        jBuutton_search_using_both = new javax.swing.JButton();
        jBuutton_search_using_both1 = new javax.swing.JButton();
        jButton7_search_using_flight_no1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_arriv_time = new javax.swing.JTextField();
        jTextField4_destination = new javax.swing.JTextField();
        jTextField5_source = new javax.swing.JTextField();
        jTextField6_fare = new javax.swing.JTextField();
        jLabel1_FLIGHT_NUMBER = new javax.swing.JLabel();
        jLabel16_FLIGHT_NAME = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton7_find_usin_flight_no = new javax.swing.JButton();
        jButton7_findflight_foredit_both2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1_Addflight_out = new javax.swing.JButton();
        jButton1_register = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1_edit_flight_details1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel5_arr1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField2_add_dept_time1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3_aadd_arriv_time1 = new javax.swing.JTextField();
        jTextField4_add_destination1 = new javax.swing.JTextField();
        jTextField5_add_flight = new javax.swing.JTextField();
        jTextField6_add_fare1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField5_add_airline = new javax.swing.JTextField();
        jTextField5_add_source3 = new javax.swing.JTextField();
        jComboBox3_day = new javax.swing.JComboBox();
        jComboBox2_month = new javax.swing.JComboBox();
        jComboBox4_year = new javax.swing.JComboBox();
        Add_flight = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenuItem1_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book n Fly");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 700));
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));
        jPanel1.add(jLabel1_email);
        jLabel1_email.setBounds(10, 10, 1000, 630);
        jLabel1_email.add(jButton2);

        jButton1_selectionsummery.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1_selectionsummery.setText("Add/Edit Flight Details                                                                                                                                                                                                ");
        jButton1_selectionsummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_selectionsummeryActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_selectionsummery);
        jButton1_selectionsummery.setBounds(10, 10, 1000, 25);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setText("Payment Details                                                                                                                                                         ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 610, 1000, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setText("Passenger Details                                                                                                                                                       ");
        jButton3.setMaximumSize(new java.awt.Dimension(750, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(750, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 570, 1000, 25);

        jButton4_login.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton4_login.setText("Login/Contact Details                                                                                                                                                ");
        jButton4_login.setInheritsPopupMenu(true);
        jButton4_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_loginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4_login);
        jButton4_login.setBounds(10, 530, 1000, 25);

        jLabel1_add_flight_details.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1_add_flight_details.setText("Add Flight details here");
        jPanel1.add(jLabel1_add_flight_details);
        jLabel1_add_flight_details.setBounds(460, 60, 160, 20);
        jLabel1_add_flight_details.setVisible(false);

        jButton1_Edit_fligt.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton1_Edit_fligt.setForeground(new java.awt.Color(204, 0, 0));
        jButton1_Edit_fligt.setText("Edit flight details");
        jButton1_Edit_fligt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Edit_fligtActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Edit_fligt);
        jButton1_Edit_fligt.setBounds(90, 160, 170, 80);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel8.setText("Fare");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(270, 350, 40, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel9.setText("To");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(330, 80, 30, 14);

        jButton7_fupdate_both.setBackground(new java.awt.Color(255, 153, 51));
        jButton7_fupdate_both.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7_fupdate_both.setText("Update");
        jButton7_fupdate_both.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_fupdate_bothActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7_fupdate_both);
        jButton7_fupdate_both.setBounds(490, 340, 160, 50);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel13.setText("Airline");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(370, 190, 80, 14);

        jComboBox4_flight_noboth.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel4.add(jComboBox4_flight_noboth);
        jComboBox4_flight_noboth.setBounds(40, 100, 100, 23);
        try{

            Connection con = NewCon.connect();
            Statement st= con.createStatement();
            String sql ="select flight_number from flight_details";
            ResultSet rs =	st.executeQuery(sql);

            while(rs.next() ){

                jComboBox4_flight_noboth.addItem(rs.getString(1));
            }
        }catch(Exception ex){
            System.out.println(ex);
        }

        jComboBox5_destination_both.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel4.add(jComboBox5_destination_both);
        jComboBox5_destination_both.setBounds(330, 100, 140, 23);
        jComboBox5_destination_both.setVisible(false);
        try{

            Connection con = NewCon.connect();
            Statement st= con.createStatement();
            String sql ="select destination from source_and_destination";
            ResultSet rs =	st.executeQuery(sql);

            while(rs.next() ){

                jComboBox5_destination_both.addItem(rs.getString(1));
            }
        }catch(Exception ex){
            System.out.println(ex);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setText("Date");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(40, 350, 34, 20);

        jLabel5_arr.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5_arr.setText("Arrival Time");
        jPanel4.add(jLabel5_arr);
        jLabel5_arr.setBounds(40, 290, 80, 20);
        jLabel5_arr.setVisible(false);
        jLabel9.setVisible(false);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel7.setText("Arrival Time");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(40, 290, 100, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel15.setText("Source");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(170, 80, 120, 14);
        jLabel15.setVisible(false);

        jComboBox4_source_both.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel4.add(jComboBox4_source_both);
        jComboBox4_source_both.setBounds(170, 100, 140, 23);
        jComboBox4_source_both.setVisible(false);
        try{

            Connection con = NewCon.connect();
            Statement st= con.createStatement();
            String sql ="select source from source_and_destination";
            ResultSet rs =	st.executeQuery(sql);

            while(rs.next() ){

                jComboBox4_source_both.addItem(rs.getString(1));
            }
        }catch(Exception ex){
            System.out.println(ex);
        }

        jTextField1_date.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField1_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField1_date);
        jTextField1_date.setBounds(80, 350, 140, 20);

        jTextField2_dept_time.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField2_dept_time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField2_dept_time);
        jTextField2_dept_time.setBounds(500, 290, 140, 20);

        jPanel2.setBackground(new java.awt.Color(229, 250, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(73, 159, 246), 1, true), "Search Using", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jButton7_search_using_flight_no.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7_search_using_flight_no.setText("Flight number");
        jButton7_search_using_flight_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_search_using_flight_noActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7_search_using_flight_no);
        jButton7_search_using_flight_no.setBounds(30, 20, 140, 20);
        jButton7_search_using_flight_no.setVisible(true);

        jBuutton_search_using_both.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jBuutton_search_using_both.setText("Flight number,source and Destination");
        jBuutton_search_using_both.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuutton_search_using_bothActionPerformed(evt);
            }
        });
        jPanel2.add(jBuutton_search_using_both);
        jBuutton_search_using_both.setBounds(190, 20, 430, 20);

        jBuutton_search_using_both1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jBuutton_search_using_both1.setText("Flight number,source and Destination");
        jBuutton_search_using_both1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuutton_search_using_both1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBuutton_search_using_both1);
        jBuutton_search_using_both1.setBounds(190, 20, 430, 20);

        jButton7_search_using_flight_no1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7_search_using_flight_no1.setText("Flight number");
        jButton7_search_using_flight_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_search_using_flight_no1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7_search_using_flight_no1);
        jButton7_search_using_flight_no1.setBounds(30, 20, 140, 20);
        jButton7_search_using_flight_no.setVisible(true);

        jPanel4.add(jPanel2);
        jPanel2.setBounds(10, 0, 650, 70);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel10.setText("Flight No");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 190, 80, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel11.setText("Flight No");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(40, 80, 150, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel12.setText("Destination");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(370, 240, 70, 14);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 178, 244), 1, true), "Edit here", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 160, 650, 250);

        jTextField3_arriv_time.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField3_arriv_time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField3_arriv_time);
        jTextField3_arriv_time.setBounds(160, 290, 140, 20);

        jTextField4_destination.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField4_destination.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField4_destination);
        jTextField4_destination.setBounds(500, 240, 140, 20);

        jTextField5_source.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField5_source.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField5_source);
        jTextField5_source.setBounds(160, 240, 140, 20);

        jTextField6_fare.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField6_fare.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.add(jTextField6_fare);
        jTextField6_fare.setBounds(330, 350, 140, 20);

        jLabel1_FLIGHT_NUMBER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel1_FLIGHT_NUMBER);
        jLabel1_FLIGHT_NUMBER.setBounds(160, 190, 140, 20);

        jLabel16_FLIGHT_NAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel16_FLIGHT_NAME);
        jLabel16_FLIGHT_NAME.setBounds(500, 190, 140, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel16.setText("Source");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(40, 240, 80, 20);
        jLabel5_arr.setVisible(false);
        jLabel9.setVisible(false);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel17.setText("Departure Time");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(370, 290, 100, 20);

        jButton7_find_usin_flight_no.setBackground(new java.awt.Color(255, 153, 51));
        jButton7_find_usin_flight_no.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7_find_usin_flight_no.setText("Find Flights to edit");
        jButton7_find_usin_flight_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_find_usin_flight_noActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7_find_usin_flight_no);
        jButton7_find_usin_flight_no.setBounds(480, 80, 170, 50);

        jButton7_findflight_foredit_both2.setBackground(new java.awt.Color(255, 153, 51));
        jButton7_findflight_foredit_both2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jButton7_findflight_foredit_both2.setText("Find Flights to edit.");
        jButton7_findflight_foredit_both2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_findflight_foredit_both2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7_findflight_foredit_both2);
        jButton7_findflight_foredit_both2.setBounds(480, 80, 170, 50);
        jButton7_findflight_foredit_both2.setVisible(false);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(280, 90, 680, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoorignl.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 250, 82);

        jButton1_Addflight_out.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1_Addflight_out.setText("Add flights");
        jButton1_Addflight_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Addflight_outActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Addflight_out);
        jButton1_Addflight_out.setBounds(90, 260, 170, 80);

        jButton1_register.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jButton1_register.setText("Login Page");
        jButton1_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_registerActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_register);
        jButton1_register.setBounds(90, 360, 170, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel14.setText("Welcome Administrator,");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 60, 170, 20);

        jLabel1_edit_flight_details1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1_edit_flight_details1.setText("Edit Flight details here");
        jPanel1.add(jLabel1_edit_flight_details1);
        jLabel1_edit_flight_details1.setBounds(460, 60, 160, 20);

        jPanel5.setBackground(new java.awt.Color(235, 249, 250));
        jPanel5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel18.setText("Fare");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(130, 340, 40, 17);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel20.setText("Airline");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(360, 50, 80, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setText("Date");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(130, 280, 34, 20);

        jLabel5_arr1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5_arr1.setText("Arrival Time");
        jPanel5.add(jLabel5_arr1);
        jLabel5_arr1.setBounds(130, 190, 80, 20);
        jLabel5_arr.setVisible(false);
        jLabel9.setVisible(false);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel21.setText("Arrival Time");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(130, 190, 100, 20);

        jTextField2_add_dept_time1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField2_add_dept_time1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField2_add_dept_time1);
        jTextField2_add_dept_time1.setBounds(360, 210, 200, 20);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel23.setText("Flight No");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(130, 50, 80, 20);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel25.setText("Destination");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(360, 120, 70, 14);

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 178, 244), 1, true), "Add details here", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 20, 650, 400);

        jTextField3_aadd_arriv_time1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField3_aadd_arriv_time1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField3_aadd_arriv_time1);
        jTextField3_aadd_arriv_time1.setBounds(130, 210, 200, 20);

        jTextField4_add_destination1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField4_add_destination1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField4_add_destination1);
        jTextField4_add_destination1.setBounds(360, 140, 200, 20);

        jTextField5_add_flight.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField5_add_flight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField5_add_flight);
        jTextField5_add_flight.setBounds(130, 70, 200, 20);

        jTextField6_add_fare1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField6_add_fare1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField6_add_fare1);
        jTextField6_add_fare1.setBounds(180, 340, 200, 20);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel26.setText("Source");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(130, 120, 80, 20);
        jLabel5_arr.setVisible(false);
        jLabel9.setVisible(false);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel27.setText("Departure Time");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(360, 190, 100, 20);

        jTextField5_add_airline.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField5_add_airline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField5_add_airline);
        jTextField5_add_airline.setBounds(360, 70, 200, 20);

        jTextField5_add_source3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jTextField5_add_source3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.add(jTextField5_add_source3);
        jTextField5_add_source3.setBounds(130, 140, 200, 20);

        jComboBox3_day.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox3_day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel5.add(jComboBox3_day);
        jComboBox3_day.setBounds(190, 280, 50, 23);

        jComboBox2_month.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox2_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel5.add(jComboBox2_month);
        jComboBox2_month.setBounds(240, 280, 60, 23);

        jComboBox4_year.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jComboBox4_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990" }));
        jPanel5.add(jComboBox4_year);
        jComboBox4_year.setBounds(300, 280, 70, 23);

        Add_flight.setBackground(new java.awt.Color(255, 153, 51));
        Add_flight.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Add_flight.setText("add Flight");
        Add_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_flightActionPerformed(evt);
            }
        });
        jPanel5.add(Add_flight);
        Add_flight.setBounds(390, 280, 170, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(290, 80, 680, 430);
        jPanel5.setVisible(false);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 680);

        menu_file.setBackground(new java.awt.Color(204, 51, 0));
        menu_file.setText("File      ");
        menu_file.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jMenuItem1_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        jMenuItem1_exit.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jMenuItem1_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        jMenuItem1_exit.setText("Exit");
        jMenuItem1_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_exitActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem1_exit);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      ///  new UserRegistration().setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1_selectionsummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_selectionsummeryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_selectionsummeryActionPerformed

    private void jButton7_fupdate_bothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_fupdate_bothActionPerformed
String source=jTextField5_source.getText();        // TODO add your handling code here:
String destination=jTextField4_destination.getText();
String day=jTextField1_date.getText();
String arrival=jTextField3_arriv_time.getText();
String depart=jTextField2_dept_time.getText();
String flight_umber=jLabel1_FLIGHT_NUMBER.getText();

int rate=0;
boolean flag=false;
try
{
rate=Integer.parseInt(jTextField6_fare.getText());
flag=true;
}
catch(Exception er){
    JOptionPane.showMessageDialog(null, "invalid fare");
    flag=true;
}









if(flag)
{
try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="update flight_details set date='"+day+"',arrival_time='"+arrival+"',departure_time='"+depart+"',source='"+source+"',destination='"+destination+"',fare='"+rate+"' where flight_number='"+flight_umber+"'";
                                                 //)";
							
                                                 st.executeUpdate(sql);
							JOptionPane.showMessageDialog(null,"FLIGHT DATABASE UPDATED");
                                                       // dispose();
                                                       // new search_home().setVisible(true);
                                                        
						}catch(Exception er){
                                                    JOptionPane.showMessageDialog(null, "invalid date");
                                                    System.out.println(er);
						}


}











    }//GEN-LAST:event_jButton7_fupdate_bothActionPerformed

    private void jButton1_Edit_fligtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Edit_fligtActionPerformed
jPanel5.setVisible(false);
jPanel2.setVisible(true);
jPanel4.setVisible(true);
        jButton1_Edit_fligt.setForeground(Color.red);
jButton1_Addflight_out.setForeground(Color.black);
jLabel1_add_flight_details.setVisible(false);   
jLabel1_edit_flight_details1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_Edit_fligtActionPerformed

    private void jMenuItem1_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_exitActionPerformed
int reply=JOptionPane.showConfirmDialog(null,"sure");  
if(reply==JOptionPane.OK_OPTION)
{
    System.exit(0);
}

{
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_exitActionPerformed

    private void jButton1_Addflight_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Addflight_outActionPerformed
jPanel5.setVisible(true);
jPanel2.setVisible(false);
jPanel4.setVisible(false);
        jButton1_Edit_fligt.setForeground(Color.black);  
jButton1_Addflight_out.setForeground(Color.red);// TODO add your handling code here:
jLabel1_add_flight_details.setVisible(true);
jLabel1_edit_flight_details1.setVisible(false);

    }//GEN-LAST:event_jButton1_Addflight_outActionPerformed

    private void jButton1_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_registerActionPerformed
new Login().setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_registerActionPerformed

    private void jButton7_search_using_flight_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_search_using_flight_no1ActionPerformed
        jButton7_find_usin_flight_no.setVisible(true);
        jButton7_findflight_foredit_both2.setVisible(false);
        jComboBox4_source_both.setVisible(false);
        jComboBox5_destination_both.setVisible(false);
        jLabel15.setVisible(false);
        jLabel9.setVisible(false);
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7_search_using_flight_no1ActionPerformed

    private void jBuutton_search_using_both1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuutton_search_using_both1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jBuutton_search_using_both1ActionPerformed

    private void jBuutton_search_using_bothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuutton_search_using_bothActionPerformed
        jButton7_findflight_foredit_both2.setVisible(true);
        jButton7_find_usin_flight_no.setVisible(false);
        jComboBox4_source_both.setVisible(true);
        jComboBox5_destination_both.setVisible(true);
        jLabel15.setVisible(true);
        jLabel9.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jBuutton_search_using_bothActionPerformed

    private void jButton7_search_using_flight_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_search_using_flight_noActionPerformed
        jButton7_find_usin_flight_no.setVisible(true);
        jButton7_findflight_foredit_both2.setVisible(false);
        jComboBox4_source_both.setVisible(false);
        jComboBox5_destination_both.setVisible(false);
        jLabel15.setVisible(false);
        jLabel9.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7_search_using_flight_noActionPerformed

    private void jButton7_findflight_foredit_both2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_findflight_foredit_both2ActionPerformed

        
        String FLIGHT_NO=(String)jComboBox4_flight_noboth.getSelectedItem();
        String source=(String)jComboBox4_source_both.getSelectedItem();
        String destination=(String)jComboBox5_destination_both.getSelectedItem();
String flight_result_number="";
String flight_result_name="";
String flight_result_arrival="";
String flight_result_departure="";
String flight_result_date="";
int flight_result_fare=0;
String f="";
String flight_result_source="";
String flight_result_destination="";

boolean flag=false;



try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="select * from flight_details where flight_number='"+FLIGHT_NO+"' and source='"+source+"' and destination='"+destination+"'";
						 ResultSet rs =	st.executeQuery(sql);
					
						 while(rs.next() ){
						 

                                                    flight_result_number = 	rs.getString("flight_number");
							 flight_result_fare =	rs.getInt("fare");
                                                          f=new Integer(flight_result_fare).toString();
                                                        //System.out.println(flight_number);
                                                         flight_result_arrival= 	rs.getString("arrival_time");
                                                                flight_result_departure= 	rs.getString("departure_time");
                                                                 flight_result_date= 	rs.getString("date");
                                                                         flight_result_source= 	rs.getString("source");
                                                                         flight_result_destination= 	rs.getString("destination");
                                                                                 flight_result_name= 	rs.getString("flight_name");
                                                                                 
							flag =true;
						 }
						}catch(Exception ex){
							System.out.println(ex);
						}
					//personal details
					if(flag){
                                           jLabel1_FLIGHT_NUMBER.setText(flight_result_number);
                                           jLabel16_FLIGHT_NAME.setText(flight_result_name);
                                           jTextField5_source.setText(flight_result_source);
                                           jTextField4_destination.setText(flight_result_destination);
                                           jTextField3_arriv_time.setText(flight_result_arrival);
                                           jTextField2_dept_time.setText(flight_result_departure);
                                           jTextField1_date.setText(flight_result_date);
                                           jTextField6_fare.setText(f);
                                            
				
				}
					else{
						JOptionPane.showMessageDialog(null,   "Sorry, Please search with another flight !");	
					}
        
        
  

        
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7_findflight_foredit_both2ActionPerformed

    private void jButton7_find_usin_flight_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_find_usin_flight_noActionPerformed

               int childcount=0; 
String FLIGHT_NO=(String)jComboBox4_flight_noboth.getSelectedItem();
String flight_result_number="";
String flight_result_name="";
String flight_result_arrival="";
String flight_result_departure="";
String flight_result_date="";
int flight_result_fare=0;
String f="";
String flight_result_source="";
String flight_result_destination="";

boolean flag=false;



try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="select * from flight_details where flight_number='"+FLIGHT_NO+"'";
						 ResultSet rs =	st.executeQuery(sql);
					
						 while(rs.next() ){
						 

                                                    flight_result_number = 	rs.getString("flight_number");
							 flight_result_fare =	rs.getInt("fare");
                                                          f=new Integer(flight_result_fare).toString();
                                                        //System.out.println(flight_number);
                                                         flight_result_arrival= 	rs.getString("arrival_time");
                                                                flight_result_departure= 	rs.getString("departure_time");
                                                                 flight_result_date= 	rs.getString("date");
                                                                         flight_result_source= 	rs.getString("source");
                                                                         flight_result_destination= 	rs.getString("destination");
                                                                                 flight_result_name= 	rs.getString("flight_name");
                                                                                 
							flag =true;
						 }
						}catch(Exception ex){
							System.out.println(ex);
						}
					//personal details
					if(flag){
                                           jLabel1_FLIGHT_NUMBER.setText(flight_result_number);
                                           jLabel16_FLIGHT_NAME.setText(flight_result_name);
                                           jTextField5_source.setText(flight_result_source);
                                           jTextField4_destination.setText(flight_result_destination);
                                           jTextField3_arriv_time.setText(flight_result_arrival);
                                           jTextField2_dept_time.setText(flight_result_departure);
                                           jTextField1_date.setText(flight_result_date);
                                           jTextField6_fare.setText(f);
                                            
				
				}
					else{
						JOptionPane.showMessageDialog(null,   "Sorry, Please search with another flight !");	
					}
        
        
  
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7_find_usin_flight_noActionPerformed

    private void Add_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_flightActionPerformed

        
        
        String source=jTextField5_add_source3.getText();        // TODO add your handling code here:
String destination=jTextField4_add_destination1.getText();
String flight_name=jTextField5_add_airline.getText();
  String day=(String)jComboBox3_day.getSelectedItem();
        String month=(String)jComboBox2_month.getSelectedItem();
        String year=(String)jComboBox4_year.getSelectedItem();
        String date=year+"/"+month+"/"+day;
String arrival=jTextField3_aadd_arriv_time1.getText();
String depart=jTextField2_add_dept_time1.getText();
String flight_umber=jTextField5_add_flight.getText();
boolean flag=false;
if(year=="yyyy")
{
    JOptionPane.showMessageDialog(null,"invalid year");
    flag=false;
}
else if(month=="mm")
{
    JOptionPane.showMessageDialog(null,"invalid month");
    flag=false;
}
else if(day=="dd")
{
    JOptionPane.showMessageDialog(null,"invalid date");
    flag=false;
}
int rate=0;

try
{
rate=Integer.parseInt(jTextField6_add_fare1.getText());
flag=true;
}
catch(Exception er){
    JOptionPane.showMessageDialog(null, "invalid fare");
    flag=true;
}









if(flag)
{
try{
					
						 Connection con = NewCon.connect();
						 Statement st= con.createStatement();
						 String sql ="insert into flight_details values('"+flight_umber+"','"+source+"','"+destination+"','"+rate+"','"+flight_name+"','"+date+"','"+arrival+"','"+depart+"')";
                                                 //)";
							
                                                 st.executeUpdate(sql);
							JOptionPane.showMessageDialog(null,"FLIGHT DATABASE UPDATED");
                                                
                                                        
						}catch(Exception er){
                                                    JOptionPane.showMessageDialog(null, "invalid updation check if flight number already exist");
                                                    System.out.println(er);
						}


}


        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_flightActionPerformed

    private void jButton4_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_loginActionPerformed
new Login().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4_loginActionPerformed

       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new search_home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_flight;
    private javax.swing.JButton jButton1_Addflight_out;
    private javax.swing.JButton jButton1_Edit_fligt;
    private javax.swing.JButton jButton1_register;
    private javax.swing.JButton jButton1_selectionsummery;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4_login;
    private javax.swing.JButton jButton7_find_usin_flight_no;
    private javax.swing.JButton jButton7_findflight_foredit_both2;
    private javax.swing.JButton jButton7_fupdate_both;
    private javax.swing.JButton jButton7_search_using_flight_no;
    private javax.swing.JButton jButton7_search_using_flight_no1;
    private javax.swing.JButton jBuutton_search_using_both;
    private javax.swing.JButton jBuutton_search_using_both1;
    private javax.swing.JComboBox jComboBox2_month;
    private javax.swing.JComboBox jComboBox3_day;
    private javax.swing.JComboBox jComboBox4_flight_noboth;
    private javax.swing.JComboBox jComboBox4_source_both;
    private javax.swing.JComboBox jComboBox4_year;
    private javax.swing.JComboBox jComboBox5_destination_both;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel16_FLIGHT_NAME;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel1_FLIGHT_NUMBER;
    private javax.swing.JLabel jLabel1_add_flight_details;
    private javax.swing.JLabel jLabel1_edit_flight_details1;
    private javax.swing.JLabel jLabel1_email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_arr;
    private javax.swing.JLabel jLabel5_arr1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1_date;
    private javax.swing.JTextField jTextField2_add_dept_time1;
    private javax.swing.JTextField jTextField2_dept_time;
    private javax.swing.JTextField jTextField3_aadd_arriv_time1;
    private javax.swing.JTextField jTextField3_arriv_time;
    private javax.swing.JTextField jTextField4_add_destination1;
    private javax.swing.JTextField jTextField4_destination;
    private javax.swing.JTextField jTextField5_add_airline;
    private javax.swing.JTextField jTextField5_add_flight;
    private javax.swing.JTextField jTextField5_add_source3;
    private javax.swing.JTextField jTextField5_source;
    private javax.swing.JTextField jTextField6_add_fare1;
    private javax.swing.JTextField jTextField6_fare;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables
}
